### PR TITLE
Upgrade all classes to support spec 3.16

### PR DESCRIPTION
**Pull request by tm1000**
I added psalm in github actions.

Also Psalm has strict requirements on some of the class constructors not allowing nulls. I am not sure how this will interact with json-rpc-dispatcher since that uses jsonmapper to construct the classes (but it uses reflection). Just have not tested this yet.

Note I changed your class name of WindowClientCapabilities to ClientCapabilitiesWindow.

Additional notes:

I maintain:

- https://github.com/psalm/psalm-vscode-plugin
- Psalm (https://github.com/vimeo/psalm) uses this library for it's own Language server which overlaps slightly with the language server you forked
- I also do some maintenance on the LSP in Psalm and additionally I'm working on reworking it here: https://github.com/tm1000/psalm/tree/feature/upgrade-lsp for the v5 release of Psalm

### CODE REVIEW

**Comment by tm1000** [comment]
Confirmed. It fails in in json-rpc-dispatcher when it tries to instantiate the class. This is why Psalm was never enabled in actions.

**Comment by tm1000** [comment]
Ok I went back through this and re-asserted all constructors to null, then I went through and suppressed all Psalm issues with that.

Some thoughts:

- This library would do well with PHP 8.1 ENUMs
- This needs to be forked: https://github.com/felixfbecker/php-advanced-json-rpc
  - On that it needs to have some issues fixed:
   - It needs to use reflection to look at the CONSTRUCTOR FIRST to add values before it tries to new the class, this would then fix all the psalm errors that have to be suppressed
   - There is an issue in fulfilling `workspaceFolders` part of the initialize spec from LSP 3.16. it throws an exception it if finds the parameter and attempts to do this. (This is the error I've mentioned before)

**Comment by tm1000** [comment]
The tests are failing for strange reasons but namely Psalm requires this library of which this library requires Psalm

The only way to fix that is probably to use Psalm phar? or not run the psalm tests in the action I am not sure. 

If you run it locally it will pass

**Comment by zobo** [comment]
Amazing. I will dig a bit deeper into this and see what can be done. I'm not so confident I want to introduce PHP 8 features just yet. A lot of people are running the code on PHP 7.x.

**Comment by tm1000** [comment]
@zobo no. You shouldn't require php 8.1 only (my work here does not require php 8.1). I think thats a years out thing from this (5+) (Sadly).

I only say this because the constants in this library do not make any sense in how things are constructed.

**Comment by zobo** [comment]
Agree. I'm just in the middle of this pain where I want to upgrade a large project to PHP8 and a lot of things are connected to other code bases still running on 7... 
BTW, I also maintain [vscode-php-debug](https://github.com/xdebug/vscode-php-debug) if you have any questions there :)

**Comment by tm1000** [comment]
@zobo oh! I was happy to see you regained ownership of that from Felix from Microsoft! I didn't connect that you are the same person. Thank you for doing that.

I had wondered why Felix's stuff got removed from the Marketplace but I saw you mention somewhere else that there was a security vulnerability and since Felix basically abandonwared his stuff MS removed the module.

Anyways it would be nice for `php-language-server-protocol` and https://github.com/felixfbecker/php-advanced-json-rpc to have a new home here with you (or perhaps another organization for them both) as both Inteliense (which you have revived) and Psalm require these libraries.

If you didnt know Matt Brown was the maintainer and founder of Psalm. He's just recently left to go work for Slack (good for him) as a result he's going to have less time overall to maintain `php-language-server-protocol` and additionally I dont think it should be maintained on Felix's organization if Felix has abandoned everything...

**Comment by zobo** [comment]
Maybe this would fix the composer resolving problem:

```
      - name: Composer Install
        run: COMPOSER_ROOT_VERSION=dev-main composer install --prefer-dist --no-interaction
```

**Comment by tm1000** [comment]
@zobo I think you can edit this PR if you need (It says Allow edits and access by maintainers) if thats not the case I will come back to this either tonight or tomorrow (USA time)

**Comment by zobo** [comment]
Ha! It did not allow me to push the code, but I could edit it online.
I need to go to bed too and hopefully will find some time tomorrow for this.
I'll see if I can get away by just using this code with the current php-language-server code and if not, I'll start looking at the php-advanced-json-rpc.

You are right that these repositories should be moved under some organisation. It's just it's a big task that needs some thought and I have not yet gone there.

**Comment by tm1000** [comment]
This should work with php-advanced-json-rpc. There was a lot of x- variables I removed that Felix added and from his discussions with Microsoft it seems like x stands for experimental but I cant see that vscode uses any of that now. I'm saying this because intelisense might use those variables somewhere. They were also used in Psalm but I removed the references to them, it was not an issue.

PS: the PR now passes

**Comment by zobo** [comment]
I think this might be used by other clients (other than vscode). I will look at it tomorrow.
If it turns out it's somehow used by php-language-server it might make sense the classes are extended in that project...

**Comment by tm1000** [comment]
@zobo if you decide to take these two projects into an organization Id be willing help. I know it's a lot of work but just want you to know you wouldn't be alone in maintaining them

**Comment by zobo** [comment]
I tried this latest branch, and aside from updating some test results and adding back the missing `xfilesProvider`, `xcontentProvider` and `xcacheProvider` to `ClientCapabilities` it looks like everything works. I will test it out a bit more, but I think I'll merge this, then apply the "missing" fields so I can do a release of vscode-php-intellisense.

**Comment by tm1000** [comment]
@zobo are the "x" attributes actually used? I've referenced the language server protocol 3.16 and I couldn't find a reference too those. Not opposed to adding them back but I'm not sure if Felix added those for something years ago that's no longer relevant

Let me know when you do a release and if you are going to push this to packagist so I can have Psalm reference it

**Comment by zobo** [comment]
I think here is the design extension: https://github.com/sourcegraph/language-server-protocol . There are 3 files on the root describing it. I also found a few implementations of it around GitHub. The PHP Language Server does implement this extensions, so I'll just add them back for now.

**Comment by tm1000** [comment]
@zobo ah! This makes sense. This is where Felix works! Ok yes. Let's add it back. I will adjust psalm to account for that

**Comment by tm1000** [comment]
@zobo is your plan to publish this to packagist?

**Comment by zobo** [comment]
Hey. I'm considering making a PR at the original repo first. If there's an active maintainer there, lets try this. What do you think?

**Comment by tm1000** [comment]
@zobo thats a good idea. I agree.

**Pull request merged**
